#pragma once
#include <Arduino.h>

const char PAGE[] PROGMEM = R"HTML(<!doctype html><html lang="ru"><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>Лифт · Настройки</title>
<style>body{font:16px system-ui;background:#101826;color:#edf3ff;margin:0;padding:24px}main{max-width:760px;margin:auto}h1{margin-bottom:8px}.muted{color:#aabbd4}section{background:#1c293c;border-radius:16px;padding:24px;margin:20px 0}dl{display:grid;grid-template-columns:1fr 1fr;gap:14px}dd{margin:0;text-align:right}button:disabled{opacity:.45;cursor:default}button{background:#73d5b6;color:#10251f;border:0;border-radius:8px;padding:14px;font:inherit;cursor:pointer}a{color:#73d5b6}</style>
<main><p class="muted">ELEVATOR ESP32</p><h1>Состояние лифта</h1><p id="connection">Подключение…</p>
<section><dl id="values"></dl></section><section><h2>Подключение к Wi-Fi</h2>
<p>Для смены сети откроется точка Lift-Setup. Пока открыт портал настройки, движение заблокировано.</p>
<button id="network" disabled>Настроить другую сеть</button><p id="message"></p></section>
<p class="muted">Данные обновляются во время движения. Смена Wi-Fi доступна только после остановки. Управление мотором и калибровка пока остаются на пульте и USB.</p></main>
<script>const states=['Запуск','Нужна калибровка','Калибровка вверх','Калибровка вниз','Ожидание','Поездка','Ручное движение','Ошибка','Нужно найти верх','Поиск верха'];let token='';
async function update(){try{const r=await fetch('/api/status',{cache:'no-store',signal:AbortSignal.timeout(2500)});if(!r.ok)throw Error();const s=await r.json();if(s.age>1000)throw Error('stale');token=s.token;document.getElementById('network').disabled=!s.stationary||s.networkResult===1;if(s.networkResult===2)document.getElementById('message').textContent='Смена сети отменена: лифт начал движение или запрос устарел';document.getElementById('connection').textContent='База доступна · '+s.ip;
const rows=[['Состояние',states[s.state]||s.state],['Этаж / цель',s.floor+' / '+s.target],['Позиция, шагов',s.position],['Позиция известна',s.known?'Да':'Нет'],['Ошибка',s.error],['Верхний концевик',s.top?'Нажат':'Свободен'],['Регулятор скорости',s.speed+'%'],['Пульт зарегистрирован',s.peer?'Да':'Нет'],['Радиоканал',s.channel],['Время работы, с',Math.floor(s.uptime/1000)],['Мотор',s.running?'Движется':'Остановлен'],['Ход, шагов',s.travel],['Свободная память, КБ',Math.round(s.freeHeap/1024)],['Сигнал Wi-Fi',s.rssi+' dBm']];const box=document.getElementById('values');box.replaceChildren();for(const [k,v]of rows){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;box.append(dt,dd)}}catch(e){token='';document.getElementById('network').disabled=true;document.getElementById('connection').textContent='Нет обновления: данные устарели или сеть недоступна'}setTimeout(update,1000)}update();
document.getElementById('network').onclick=async()=>{if(!token||document.getElementById('network').disabled||!confirm('Перейти в режим настройки сети?'))return;try{const r=await fetch('/api/network',{method:'POST',headers:{'X-Lift-Token':token}});document.getElementById('message').textContent=await r.text();if(r.ok)document.getElementById('network').disabled=true}catch(e){document.getElementById('message').textContent='Проверьте наличие точки Lift-Setup'}};</script></html>)HTML";
